name: Portfolio CI/CD

# Quando essa esteira deve rodar?
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  qualidade-e-build:
    runs-on: ubuntu-latest # O servidor que vai rodar os testes

    steps:
      - name: 📥 Baixar o código
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 📦 Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: 🔌 Instalar dependências
        run: pnpm install

      - name: 🔎 Verificação de Tipagem (TypeScript)
        # Roda o script "check" que já existe no seu package.json
        run: pnpm run check

      - name: 🏗️ Testar o Build
        # Tenta compilar o projeto. Se quebrar aqui, o código está com erro!
        run: pnpm run build